# Generated by Django 5.2.4 on 2026-04-22 19:16

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_remove_internshipapplication_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='first_name',
            field=models.CharField(help_text='Enter your full legal name (Letters only)', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must only contain letters and spaces.', regex='^[a-zA-Z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='last_name',
            field=models.CharField(help_text='Enter your full legal name (Letters only)', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must only contain letters and spaces.', regex='^[a-zA-Z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='motivation_letter',
            field=models.FileField(upload_to='motivation_letters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='passport_id',
            field=models.FileField(upload_to='passport_ids/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='ET'),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='recommendation_letter',
            field=models.FileField(upload_to='recommendations/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='resume',
            field=models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
